name: Build and Release .NET 8 Application

on:
  push:
    tags:
      - 'v*' # Run this action when a version tag is pushed (e.g., v1.0.0)

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Setup .NET 8 SDK
      - name: Setup .NET 8 SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      # Restore dependencies
      - name: Restore dependencies
        run: dotnet restore

      # Publish the MultiProjectTemplate project with custom executable name
      - name: Publish MultiProjectTemplate as self-contained application
        run: dotnet publish ./MultiProjectTemplate.ConsoleApp/MultiProjectTemplate.ConsoleApp.csproj --configuration Release --runtime win-x64 --self-contained true --output ./output
      
        # Zip the output for release
      - name: Zip output
        run: zip -r ./output/MultiProjectTemplate.zip ./output/*

      # Upload the build artifact as a release asset
      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: ./output/MultiProjectTemplate.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
